# -*- coding: utf-8 -*-
"""Exp 9 in NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhbPADfDmHnNGCdBUFnAlKowhbZ0_wr1
"""

import spacy
from spacy import displacy

nlp = spacy.load('en_core_web_sm')

text = 'A newsletter is a recurring email sent to a list of subscribers, delivering news, insights, curated content, or updates on a specific topic..'

doc = nlp(text)
print(f"{'Text':<15} | {'POS':<6} | {'Dep':<10} | {'Head'}")
print('-' * 50)
for token in doc:
    print(f"{token.text:<15} | {token.pos_:<6} | {token.dep_:<10} | {token.head.text}")

# Visualize the dependency graph
displacy.render(doc, style='dep', jupyter=True, options={'distance': 100})