# -*- coding: utf-8 -*-
"""Exp 8 in NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksB47zliQxX7Nq0l5aJGab7llHxOfa6B
"""

!pip install gensim

"""E0123007

"""

from gensim.models import Word2Vec
sentences = [
["king", "queen", "man", "woman"],
["paris","france", "rome", "italy"],
["apple", "orange", "banana", "fruit"],
["car","bus", "train", "vehicle"],
["man", "king", "boy"],
["woman", "girl"]
]

model = Word2Vec(sentences, vector_size=50, window=3, min_count=1, workers=2)
similarity = model.wv.similarity("king", "queen")
print("Similarity between king and queen:", similarity)
# Find most similar words
similar_words = model.wv.most_similar ("king", topn=3)
print("Words similar to 'king':")
for word, score in similar_words:
  print (word, score)
#Word analogy example
result = model.wv.most_similar (positive=["king", "woman"], negative=["man"], topn=1)
print("king- man + woman", result)